name: "Set up Go"
description: "Sets up Go"
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@4a2405e6aebff6aabd8e43618539aa35cf90ac92
      with:
        go-version-file: go.mod
