name: Commit Checker
on:
  workflow_run:
    workflows: ["Trigger build images for PRs"]
    types:
      - completed
env:
  GH_USER_EMAIL: 140449482+dsp-developers@users.noreply.github.com
  GH_USER_NAME: dsp-developers
jobs:
    commit_checker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Get Commits
              id: get-commits
              run: |
                master_commit=$(cat .git/refs/remotes/origin/master)
                echo "master_commit_hash=$master_commit" >> $GITHUB_OUTPUT
                last_commit=$(cat .git/refs/remotes/pull/${{ github.event.pull_request.number }}/merge)
                echo "last_commit_hash=$last_commit" >> $GITHUB_OUTPUT
            - name: Run Commit Checker
              shell: bash
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_EDIT }}
              continue-on-error: true
              run: |
                git config user.email "${{ env.GH_USER_EMAIL }}"
                git config user.name "${{ env.GH_USER_NAME }}"

                cat <<"EOF" >> /tmp/body-file.txt
                ::group::Commit Checker results
                ::warning ::==== These are the results of the commit checker scans         ====
                ::warning ::==== If these are not commits from upstream kfp, then          ====
                ::warning ::==== please ensure you adhere to the commit checker formatting ====
                $(podman run -q -v ${{ github.workspace }}:/src/app-root quay.io/rmartine/commitchecker:latest --start ${{ steps.get-commits.outputs.master_commit_hash }} --end ${{ steps.get-commits.outputs.last_commit_hash }})
                ::endgroup::
                EOF

                gh pr comment ${{ github.event.pull_request.number }} --body-file /tmp/body-file.txt
