name: KFP Backend Tests

on:
  push:
    branches:
      - master
      - main
      - stable
      - 'rhoai-*'
  pull_request:
    branches:
      - master
      - main
      - stable
      - 'rhoai-*'
    paths:
      - 'backend/**'
      - 'test/presubmit-backend-test.sh'

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Run Backend Tests
      run: ./test/presubmit-backend-test.sh
